configfile: "config.yaml"

rule megahit:
    input:
        p1 = config["P1"],
        p2 = config["P2"]
    output:
        "test/final.contigs.fa"
    shell:
        """
        rm -r test
        megahit -1 {input.p1} -2 {input.p2} -o test
        """
